// This file is generated by rust-protobuf 2.4.2. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

static file_descriptor_proto_data: &'static [u8] = b"\
    \n2github.com/heroiclabs/nakama/apigrpc/apigrpc.proto\x12\nnakama.api\
    \x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\
    \x1a*github.com/heroiclabs/nakama/api/api.proto2\x885\n\x06Nakama\x12W\n\
    \nAddFriends\x12\x1d.nakama.api.AddFriendsRequest\x1a\x16.google.protobu\
    f.Empty\"\x12\x82\xd3\xe4\x93\x02\x0c\"\n/v2/friend\x12k\n\rAddGroupUser\
    s\x12\x20.nakama.api.AddGroupUsersRequest\x1a\x16.google.protobuf.Empty\
    \"\x20\x82\xd3\xe4\x93\x02\x1a\"\x18/v2/group/{group_id}/add\x12\x82\x01\
    \n\x12AuthenticateCustom\x12%.nakama.api.AuthenticateCustomRequest\x1a\
    \x13.nakama.api.Session\"0\x82\xd3\xe4\x93\x02*\"\x1f/v2/account/authent\
    icate/custom:\x07account\x12\x82\x01\n\x12AuthenticateDevice\x12%.nakama\
    .api.AuthenticateDeviceRequest\x1a\x13.nakama.api.Session\"0\x82\xd3\xe4\
    \x93\x02*\"\x1f/v2/account/authenticate/device:\x07account\x12\x7f\n\x11\
    AuthenticateEmail\x12$.nakama.api.AuthenticateEmailRequest\x1a\x13.nakam\
    a.api.Session\"/\x82\xd3\xe4\x93\x02)\"\x1e/v2/account/authenticate/emai\
    l:\x07account\x12\x88\x01\n\x14AuthenticateFacebook\x12'.nakama.api.Auth\
    enticateFacebookRequest\x1a\x13.nakama.api.Session\"2\x82\xd3\xe4\x93\
    \x02,\"!/v2/account/authenticate/facebook:\x07account\x12\x8e\x01\n\x16A\
    uthenticateGameCenter\x12).nakama.api.AuthenticateGameCenterRequest\x1a\
    \x13.nakama.api.Session\"4\x82\xd3\xe4\x93\x02.\"#/v2/account/authentica\
    te/gamecenter:\x07account\x12\x82\x01\n\x12AuthenticateGoogle\x12%.nakam\
    a.api.AuthenticateGoogleRequest\x1a\x13.nakama.api.Session\"0\x82\xd3\
    \xe4\x93\x02*\"\x1f/v2/account/authenticate/google:\x07account\x12\x7f\n\
    \x11AuthenticateSteam\x12$.nakama.api.AuthenticateSteamRequest\x1a\x13.n\
    akama.api.Session\"/\x82\xd3\xe4\x93\x02)\"\x1e/v2/account/authenticate/\
    steam:\x07account\x12a\n\x0cBlockFriends\x12\x1f.nakama.api.BlockFriends\
    Request\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12\"\
    \x10/v2/friend/block\x12V\n\x0bCreateGroup\x12\x1e.nakama.api.CreateGrou\
    pRequest\x1a\x11.nakama.api.Group\"\x14\x82\xd3\xe4\x93\x02\x0e\"\t/v2/g\
    roup:\x01*\x12]\n\rDeleteFriends\x12\x20.nakama.api.DeleteFriendsRequest\
    \x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\x0c*\n/v2/frien\
    d\x12c\n\x0bDeleteGroup\x12\x1e.nakama.api.DeleteGroupRequest\x1a\x16.go\
    ogle.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v2/group/{group_i\
    d}\x12\x87\x01\n\x17DeleteLeaderboardRecord\x12*.nakama.api.DeleteLeader\
    boardRecordRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\
    \"*\x20/v2/leaderboard/{leaderboard_id}\x12o\n\x13DeleteNotifications\
    \x12&.nakama.api.DeleteNotificationsRequest\x1a\x16.google.protobuf.Empt\
    y\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v2/notification\x12v\n\x14DeleteSto\
    rageObjects\x12'.nakama.api.DeleteStorageObjectsRequest\x1a\x16.google.p\
    rotobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17\x1a\x12/v2/storage/delete:\
    \x01*\x12N\n\nGetAccount\x12\x16.google.protobuf.Empty\x1a\x13.nakama.ap\
    i.Account\"\x13\x82\xd3\xe4\x93\x02\r\x12\x0b/v2/account\x12L\n\x08GetUs\
    ers\x12\x1b.nakama.api.GetUsersRequest\x1a\x11.nakama.api.Users\"\x10\
    \x82\xd3\xe4\x93\x02\n\x12\x08/v2/user\x12S\n\x0bHealthcheck\x12\x16.goo\
    gle.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\
    \x02\x0e\x12\x0c/healthcheck\x12\x7f\n\x15ImportFacebookFriends\x12(.nak\
    ama.api.ImportFacebookFriendsRequest\x1a\x16.google.protobuf.Empty\"$\
    \x82\xd3\xe4\x93\x02\x1e\"\x13/v2/friend/facebook:\x07account\x12d\n\tJo\
    inGroup\x12\x1c.nakama.api.JoinGroupRequest\x1a\x16.google.protobuf.Empt\
    y\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v2/group/{group_id}/join\x12x\n\x0eJo\
    inTournament\x12!.nakama.api.JoinTournamentRequest\x1a\x16.google.protob\
    uf.Empty\"+\x82\xd3\xe4\x93\x02%\"#/v2/tournament/{tournament_id}/join\
    \x12n\n\x0eKickGroupUsers\x12!.nakama.api.KickGroupUsersRequest\x1a\x16.\
    google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v2/group/{group_i\
    d}/kick\x12g\n\nLeaveGroup\x12\x1d.nakama.api.LeaveGroupRequest\x1a\x16.\
    google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v2/group/{group_\
    id}/leave\x12c\n\nLinkCustom\x12\x19.nakama.api.AccountCustom\x1a\x16.go\
    ogle.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v2/account/link/cu\
    stom:\x01*\x12c\n\nLinkDevice\x12\x19.nakama.api.AccountDevice\x1a\x16.g\
    oogle.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v2/account/link/d\
    evice:\x01*\x12`\n\tLinkEmail\x12\x18.nakama.api.AccountEmail\x1a\x16.go\
    ogle.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/v2/account/link/ema\
    il:\x01*\x12s\n\x0cLinkFacebook\x12\x1f.nakama.api.LinkFacebookRequest\
    \x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$\"\x19/v2/account/\
    link/facebook:\x07account\x12o\n\x0eLinkGameCenter\x12\x1d.nakama.api.Ac\
    countGameCenter\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02\x20\
    \"\x1b/v2/account/link/gamecenter:\x01*\x12c\n\nLinkGoogle\x12\x19.nakam\
    a.api.AccountGoogle\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\
    \x02\x1c\"\x17/v2/account/link/google:\x01*\x12`\n\tLinkSteam\x12\x18.na\
    kama.api.AccountSteam\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\
    \x02\x1b\"\x16/v2/account/link/steam:\x01*\x12\x7f\n\x13ListChannelMessa\
    ges\x12&.nakama.api.ListChannelMessagesRequest\x1a\x1e.nakama.api.Channe\
    lMessageList\"\x20\x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/channel/{channel_i\
    d}\x12N\n\x0bListFriends\x12\x16.google.protobuf.Empty\x1a\x13.nakama.ap\
    i.Friends\"\x12\x82\xd3\xe4\x93\x02\x0c\x12\n/v2/friend\x12U\n\nListGrou\
    ps\x12\x1d.nakama.api.ListGroupsRequest\x1a\x15.nakama.api.GroupList\"\
    \x11\x82\xd3\xe4\x93\x02\x0b\x12\t/v2/group\x12q\n\x0eListGroupUsers\x12\
    !.nakama.api.ListGroupUsersRequest\x1a\x19.nakama.api.GroupUserList\"!\
    \x82\xd3\xe4\x93\x02\x1b\x12\x19/v2/group/{group_id}/user\x12\x90\x01\n\
    \x16ListLeaderboardRecords\x12).nakama.api.ListLeaderboardRecordsRequest\
    \x1a!.nakama.api.LeaderboardRecordList\"(\x82\xd3\xe4\x93\x02\"\x12\x20/\
    v2/leaderboard/{leaderboard_id}\x12\xb7\x01\n!ListLeaderboardRecordsArou\
    ndOwner\x124.nakama.api.ListLeaderboardRecordsAroundOwnerRequest\x1a!.na\
    kama.api.LeaderboardRecordList\"9\x82\xd3\xe4\x93\x023\x121/v2/leaderboa\
    rd/{leaderboard_id}/owner/{owner_id}\x12W\n\x0bListMatches\x12\x1e.nakam\
    a.api.ListMatchesRequest\x1a\x15.nakama.api.MatchList\"\x11\x82\xd3\xe4\
    \x93\x02\x0b\x12\t/v2/match\x12q\n\x11ListNotifications\x12$.nakama.api.\
    ListNotificationsRequest\x1a\x1c.nakama.api.NotificationList\"\x18\x82\
    \xd3\xe4\x93\x02\x12\x12\x10/v2/notification\x12\xa2\x01\n\x12ListStorag\
    eObjects\x12%.nakama.api.ListStorageObjectsRequest\x1a\x1d.nakama.api.St\
    orageObjectList\"F\x82\xd3\xe4\x93\x02@\x12\x18/v2/storage/{collection}Z\
    $\x12\"/v2/storage/{collection}/{user_id}\x12i\n\x0fListTournaments\x12\
    \".nakama.api.ListTournamentsRequest\x1a\x1a.nakama.api.TournamentList\"\
    \x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v2/tournament\x12\x8b\x01\n\x15List\
    TournamentRecords\x12(.nakama.api.ListTournamentRecordsRequest\x1a\x20.n\
    akama.api.TournamentRecordList\"&\x82\xd3\xe4\x93\x02\x20\x12\x1e/v2/tou\
    rnament/{tournament_id}\x12\xb2\x01\n\x20ListTournamentRecordsAroundOwne\
    r\x123.nakama.api.ListTournamentRecordsAroundOwnerRequest\x1a\x20.nakama\
    .api.TournamentRecordList\"7\x82\xd3\xe4\x93\x021\x12//v2/tournament/{to\
    urnament_id}/owner/{owner_id}\x12p\n\x0eListUserGroups\x12!.nakama.api.L\
    istUserGroupsRequest\x1a\x19.nakama.api.UserGroupList\"\x20\x82\xd3\xe4\
    \x93\x02\x1a\x12\x18/v2/user/{user_id}/group\x12w\n\x11PromoteGroupUsers\
    \x12$.nakama.api.PromoteGroupUsersRequest\x1a\x16.google.protobuf.Empty\
    \"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/v2/group/{group_id}/promote\x12o\n\x12\
    ReadStorageObjects\x12%.nakama.api.ReadStorageObjectsRequest\x1a\x1a.nak\
    ama.api.StorageObjects\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0b/v2/storage:\
    \x01*\x12Z\n\x07RpcFunc\x12\x0f.nakama.api.Rpc\x1a\x0f.nakama.api.Rpc\"-\
    \x82\xd3\xe4\x93\x02'\"\x0c/v2/rpc/{id}:\x07payloadZ\x0e\x12\x0c/v2/rpc/\
    {id}\x12g\n\x0cUnlinkCustom\x12\x19.nakama.api.AccountCustom\x1a\x16.goo\
    gle.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/v2/account/unlink/cu\
    stom:\x01*\x12g\n\x0cUnlinkDevice\x12\x19.nakama.api.AccountDevice\x1a\
    \x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e\"\x19/v2/account/u\
    nlink/device:\x01*\x12d\n\x0bUnlinkEmail\x12\x18.nakama.api.AccountEmail\
    \x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d\"\x18/v2/accou\
    nt/unlink/email:\x01*\x12m\n\x0eUnlinkFacebook\x12\x1b.nakama.api.Accoun\
    tFacebook\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02\x20\"\x1b\
    /v2/account/unlink/facebook:\x01*\x12s\n\x10UnlinkGameCenter\x12\x1d.nak\
    ama.api.AccountGameCenter\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\
    \x93\x02\"\"\x1d/v2/account/unlink/gamecenter:\x01*\x12g\n\x0cUnlinkGoog\
    le\x12\x19.nakama.api.AccountGoogle\x1a\x16.google.protobuf.Empty\"$\x82\
    \xd3\xe4\x93\x02\x1e\"\x19/v2/account/unlink/google:\x01*\x12d\n\x0bUnli\
    nkSteam\x12\x18.nakama.api.AccountSteam\x1a\x16.google.protobuf.Empty\"#\
    \x82\xd3\xe4\x93\x02\x1d\"\x18/v2/account/unlink/steam:\x01*\x12a\n\rUpd\
    ateAccount\x12\x20.nakama.api.UpdateAccountRequest\x1a\x16.google.protob\
    uf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10\x1a\x0b/v2/account:\x01*\x12f\n\
    \x0bUpdateGroup\x12\x1e.nakama.api.UpdateGroupRequest\x1a\x16.google.pro\
    tobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\x1a\x14/v2/group/{group_id}:\
    \x01*\x12\x94\x01\n\x16WriteLeaderboardRecord\x12).nakama.api.WriteLeade\
    rboardRecordRequest\x1a\x1d.nakama.api.LeaderboardRecord\"0\x82\xd3\xe4\
    \x93\x02*\"\x20/v2/leaderboard/{leaderboard_id}:\x06record\x12t\n\x13Wri\
    teStorageObjects\x12&.nakama.api.WriteStorageObjectsRequest\x1a\x1d.naka\
    ma.api.StorageObjectAcks\"\x16\x82\xd3\xe4\x93\x02\x10\x1a\x0b/v2/storag\
    e:\x01*\x12\x90\x01\n\x15WriteTournamentRecord\x12(.nakama.api.WriteTour\
    namentRecordRequest\x1a\x1d.nakama.api.LeaderboardRecord\".\x82\xd3\xe4\
    \x93\x02(\x1a\x1e/v2/tournament/{tournament_id}:\x06recordBE\n\x19com.he\
    roiclabs.nakama.apiB\rNakamaApiGrpcP\x01Z\x07apigrpc\xa2\x02\x04NKPB\xaa\
    \x02\x06Nakamab\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
